import ClientModel from '../../models/ClientModel';
import { v4 as guid  } from 'uuid';

export const ClientService = {
  getClientsData() : ClientModel[] {
    return [
      {
        id: guid(),
        companyName: "Baystate Health",
        streetAddress: "123 Main St", 
        city: "Springfield", 
        zip: "62701", 
        state: "IL", 
        country: "USA",
        image: "https://via.placeholder.com/150",
        invoices: [
          {
            id: guid(),
            invoiceNumber: "INV-001",
            createdDate: new Date("2024-01-15"),
            dueDate: new Date("2024-02-15"),
            isReminder: true,
            totalAmount: 300.0,
            subtotalAmount: 275.0,
            taxAmount: 25.0,
            invoiceStatus:"Sent",
            invoicePaymentStatus: "Paid",
            clientId: "client-1",
            billingPeriodStart: new Date("2024-01-20"),
            billingPeriodEnd: new Date("2024-01-20"),
            invoiceItemList: [
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget A", number: 101, price: 50.0 },
                quantity: 3,
                createdDate: new Date("2025-04-01"),
              },
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget B", number: 102, price: 75.0 },
                quantity: 2,
                createdDate: new Date("2025-04-01"),
              },
            ],
          },
          {
            id: guid(),
            invoiceNumber: "INV-025",
            createdDate: new Date("2024-01-15"),
            dueDate: new Date("2024-02-15"),
            isReminder: true,
            totalAmount: 854.0,
            subtotalAmount: 275.0,
            taxAmount: 25.0,
            invoiceStatus:"Created",
            invoicePaymentStatus: "Unpaid",
            clientId: "client-1",
            billingPeriodStart: new Date("2024-01-20"),
            billingPeriodEnd: new Date("2024-01-20"),
            invoiceItemList: [
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget A", number: 101, price: 50.0 },
                quantity: 3,
                createdDate: new Date("2025-04-01"),
              },
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget B", number: 102, price: 75.0 },
                quantity: 2,
                createdDate: new Date("2025-04-01"),
              },
            ],
          },
          {
            id: guid(),
            invoiceNumber: "INV-016",
            createdDate: new Date("2024-01-15"),
            dueDate: new Date("2024-02-15"),
            isReminder: true,
            totalAmount: 342.0,
            subtotalAmount: 275.0,
            taxAmount: 25.0,
            invoiceStatus:"Created",
            invoicePaymentStatus: "Paid",
            clientId: "client-1",
            billingPeriodStart: new Date("2024-01-20"),
            billingPeriodEnd: new Date("2024-01-20"),
            invoiceItemList: [
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget A", number: 101, price: 50.0 },
                quantity: 3,
                createdDate: new Date("2025-04-01"),
              },
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget B", number: 102, price: 75.0 },
                quantity: 2,
                createdDate: new Date("2025-04-01"),
              },
            ],
          },
        ],
      },
      {
        id: guid(),
        companyName: "MassMutual",
        streetAddress: "123 Main St", 
        city: "Springfield", 
        zip: "62701", 
        state: "IL", 
        country: "USA",
        image: "https://via.placeholder.com/150",
        invoices: [
          {
            id: guid(),
            invoiceNumber: "INV-002",
            createdDate: new Date("2024-02-10"),
            dueDate: new Date("2024-03-10"),
            isReminder: false,
            totalAmount: 450.0,
            subtotalAmount: 400.0,
            taxAmount: 50.0,
            invoiceStatus:"Sent",
            invoicePaymentStatus: "Unpaid",
            clientId: "client-2",
            billingPeriodStart: new Date("2024-01-20"),
            billingPeriodEnd: new Date("2024-01-20"),
            invoiceItemList: [
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget B", number: 102, price: 75.0 },
                quantity: 5,
                createdDate: new Date("2025-04-01"),
              },
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget C", number: 103, price: 25.0 },
                quantity: 4,
                createdDate: new Date("2025-04-01"),
              },
            ],
          },
          {
            id: guid(),
            invoiceNumber: "INV-0012",
            createdDate: new Date("2024-02-10"),
            dueDate: new Date("2024-03-10"),
            isReminder: false,
            totalAmount: 450.0,
            subtotalAmount: 400.0,
            taxAmount: 50.0,
            invoiceStatus:"Sent",
            invoicePaymentStatus: "Paid",
            clientId: "client-2",
            billingPeriodStart: new Date("2024-01-20"),
            billingPeriodEnd: new Date("2024-01-20"),
            invoiceItemList: [
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget B", number: 102, price: 75.0 },
                quantity: 5,
                createdDate: new Date("2025-04-01"),
              },
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget C", number: 103, price: 25.0 },
                quantity: 4,
                createdDate: new Date("2025-04-01"),
              },
            ],
          },
          {
            id: guid(),
            invoiceNumber: "INV-0041",
            createdDate: new Date("2024-02-10"),
            dueDate: new Date("2024-03-10"),
            isReminder: false,
            totalAmount: 450.0,
            subtotalAmount: 400.0,
            taxAmount: 50.0,
            invoiceStatus:"Sent",
            invoicePaymentStatus: "Unpaid",
            clientId: "client-2",
            billingPeriodStart: new Date("2024-01-20"),
            billingPeriodEnd: new Date("2024-01-20"),
            invoiceItemList: [
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget B", number: 102, price: 75.0 },
                quantity: 5,
                createdDate: new Date("2025-04-01"),
              },
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget C", number: 103, price: 25.0 },
                quantity: 4,
                createdDate: new Date("2025-04-01"),
              },
            ],
          },
        ],
      },
      {
        id: guid(),
        streetAddress: "123 Main St", 
        city: "Springfield", 
        companyName: "Smith & Wesson",
        zip: "62701", 
        state: "IL", 
        country: "USA",
        image: "https://via.placeholder.com/150",
        invoices: [
          {
            id: guid(),
            invoiceNumber: "INV-003",
            createdDate: new Date("2024-03-01"),
            dueDate: new Date("2024-04-01"),
            isReminder: true,
            totalAmount: 200.0,
            subtotalAmount: 180.0,
            taxAmount: 20.0,
            invoiceStatus:"Created",
            invoicePaymentStatus: "Unpaid",
            clientId: "client-3",
            billingPeriodStart: new Date("2024-01-20"),
            billingPeriodEnd: new Date("2024-01-20"),
            invoiceItemList: [
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget A", number: 101, price: 50.0 },
                quantity: 2,
                createdDate: new Date("2025-04-01"),
              },
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget D", number: 104, price: 40.0 },
                quantity: 3,
                createdDate: new Date("2025-04-01"),
              },
            ],
          },
        ],
      },
      {
        id: guid(),
        streetAddress: "123 Main St", 
        city: "Springfield", 
        zip: "62701", 
        companyName: "Big Y", 
        state: "IL", 
        country: "USA",
        image: "https://via.placeholder.com/150",
        invoices: [
          {
            id: guid(),
            invoiceNumber: "INV-004",
            createdDate: new Date("2024-01-20"),
            dueDate: new Date("2024-02-20"),
            isReminder: false,
            totalAmount: 600.0,
            subtotalAmount: 550.0,
            taxAmount: 50.0,
            invoiceStatus:"Sent",
            invoicePaymentStatus: "Paid",
            clientId: "client-4",
            billingPeriodStart: new Date("2024-01-20"),
            billingPeriodEnd: new Date("2024-01-20"),
            invoiceItemList: [
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget C", number: 103, price: 25.0 },
                quantity: 10,
                createdDate: new Date("2025-04-01"),
              },
              {
                id: guid(),
                itemModel: { id: guid(), name: "Widget E", number: 105, price: 100.0 },
                quantity: 1,
                createdDate: new Date("2025-04-01"),
              },
            ],
          },
        ],
      },
    ];
  },

  getClients() {
    return Promise.resolve(this.getClientsData());
  },

};

